# Generated by Django 4.0.2 on 2022-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Brukernavn')),
                ('password', models.CharField(max_length=200, verbose_name='Passord')),
                ('fname', models.CharField(max_length=200, verbose_name='Fornavn')),
                ('lname', models.CharField(max_length=200, verbose_name='Etternavn')),
                ('email', models.CharField(max_length=200, verbose_name='E-post')),
            ],
        ),
    ]
