# Generated by Django 4.0.2 on 2022-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_colormode_user_darkmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='darkmode',
            field=models.BooleanField(default=False, verbose_name='Mørkt tema'),
        ),
    ]
