# Generated by Django 4.0.2 on 2022-03-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publishedDate', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('ingredients', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('public', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('all', 'Alle'), ('breakfast', 'Frokost'), ('lunch', 'Lunsj'), ('dinner', 'Middag')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
