# Generated by Django 4.0.2 on 2022-02-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publishedDate', models.DateTimeField(verbose_name='date published')),
                ('ingredients', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
