# Generated by Django 4.0.2 on 2022-03-23 08:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_colormode_user_darkmode'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(choices=[('15 min', '15 min'), ('30 min', '30 min'), ('45 min', '45 min'), ('1 hour', '1 time'), ('1 hour 30 min', '1 time 30 min'), ('2+ hours', '2+ timer')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='/images/defaultRecipeImage.jpg', upload_to='images'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recipe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
