# Generated by Django 4.0.2 on 2022-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publishedDate',
            field=models.DateTimeField(default='2006-10-25', verbose_name='date published'),
        ),
    ]
