# Generated by Django 4.0.2 on 2022-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='/images/defaultRecipeImage.jpg', upload_to='images'),
        ),
    ]
