# Generated by Django 4.0.2 on 2022-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
