# Generated by Django 4.0.2 on 2022-03-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_category'),
        ('recipe', '0002_recipe_public'),
    ]

    operations = [
    ]
