# Generated by Django 4.0.2 on 2022-03-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default="{% static 'recipe/defaultRecipeImage.jpg' %}", upload_to='images/'),
        ),
    ]
