# Generated by Django 4.0.2 on 2022-03-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('recipe', '0004_remove_recipe_rating_ratings_recipe_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
