# Generated by Django 4.0.2 on 2022-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('all', 'Alle'), ('breakfast', 'Frokost'), ('lunch', 'Lunsj'), ('dinner', 'Middag')], max_length=10),
        ),
    ]
