# Generated by Django 4.0.2 on 2022-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='/images/defaultRecipeImage.jpg', upload_to='images'),
        ),
    ]
